default_platform(:ios)

platform :ios do

  lane :beta do
    match(
        app_identifier: ["app.bundle.id"],
        git_url: "https://github.com/example/example-cert.git",
        type: "development",
        git_branch: "master",
        readonly: true,
        force: false
    )
          
    clean_build_artifacts
    
    build_app(
        scheme: "Runner",
        archive_path: "./build/Runner.xcarchive",
        export_method: "development",
        configuration: "Release",
        output_directory: "./build/Runner"
    )
 
    firebase_app_distribution(
        app: "1:112014338175:ios:c67bdcb49f75a4efb7774a",
        firebase_cli_token: "1//0g4DAd7-MvJGuCgYIARAAGBASNwF-L9IrdBMl8svtsWLwoMTVYbxiS19CkrcdPJ90eswXY-TR5El_-ELkAWLURjWJkCcht1hJSD8",
        ipa_path: "./build/Runner/Runner.ipa",
        groups: "testers"
    )
  end
end