default_platform(:android)

platform :android do

  lane :beta do
    firebase_app_distribution(
        app: ${{secrets.FIREBASE_APP_ID}},
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }},
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "testers"
    )
  end  
end

