default_platform(:android)

platform :android do
  # Lane để build và phân phối app
  lane :beta do

    # Build APK
    sh "flutter build apk --release"

    # Phân phối đến Firebase App Distribution
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      service_credentials_json_data: ENV["FIREBASE_CREDENTIALS_JSON"],
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "testers",
      release_notes: "build"
    )
  end
end
