name: Build and Distribute Android with Fastlane and Firebase

on:
  push:
    branches:
      - master # Hoặc nhánh bạn muốn trigger workflow

jobs:
  build-and-distribute:
    name: Build and Distribute with Fastlane
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4" # Hoặc phiên bản cụ thể của Flutter nếu cần

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17" # Cài đặt Java 17
          distribution: "oracle"

      # Step 5: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Set environment variables
        run: |
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_CREDENTIALS_JSON=${{ secrets.FIREBASE_CREDENTIALS_JSON }}" >> $GITHUB_ENV

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Fastlane Firebase App Distribution plugin
        working-directory: android
        run: fastlane add_plugin firebase_app_distribution

      # Step 7: Build APK
      # - name: Build APK
      #   run: flutter build apk --release

      # # Step 8: Distribute to Firebase
      # - name: Distribute Android to Firebase
      #   uses: maierj/fastlane-action@v3.1.0
      #   with:
      #     lane: "beta"
      #     subdirectory: "android"

      # - name: upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-release.apk

      - name: Run Fastlane for Android
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: "beta"
          subdirectory: "android"
