name: Build and Distribute Android with Fastlane and Firebase

on:
  push:
    branches:
      - master # Hoặc nhánh bạn muốn trigger workflow

jobs:
  build-and-distribute:
    name: Build and Distribute with Fastlane
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4" # Hoặc phiên bản cụ thể của Flutter nếu cần

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      # Step 5: Install Fastlane and Firebase CLI
      - name: Install Fastlane and Firebase CLI
        run: |
          gem install fastlane --user-install
          curl -sL https://firebase.tools | bash

      # Step 6: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Distribute to Firebase
      - name: Distribute Android to Firebase
        run: fastlane beta
        working-directory: android
