name: Build and Distribute Android with Fastlane and Firebase

on:
  push:
    branches:
      - master # Hoặc nhánh bạn muốn trigger workflow

jobs:
  build-and-distribute:
    name: Build and Distribute with Fastlane
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4 # Hoặc phiên bản cụ thể của Flutter nếu cần

      - name: Install Fastlane
        run: |
          sudo gem install fastlane -NV
          fastlane install_plugins

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build và Distribute app qua Firebase
      - name: Build and Distribute Android
        working-directory: android
        run: fastlane beta
