name: Flutter Fastlane Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest # Sử dụng macOS để build cả iOS và Android.

    steps:
      # 1. Checkout code từ repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Flutter environment.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4

      - name: bundle install before run fastlane
        run: bundle install --path vendor/bundle
        working-directory: android

      # 4. Cài đặt dependencies (pub get).
      - name: Install dependencies
        run: flutter pub get

      # 5. Build và deploy cho Android.
      - name: Run fastlane
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "beta"
          subdirectory: android
